name: Build Rusda 16.2.1
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-multilib g++-multilib git curl wget unzip python3-pip xz-utils libc6-dev-i386
          pip3 install meson==1.3.0 lief tomlkit

      - name: 安装 NDK r25c
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip
          echo "ANDROID_NDK_ROOT=$GITHUB_WORKSPACE/android-ndk-r25c" >> $GITHUB_ENV

      - name: 拉取官方 16.2.1 完整源码
        run: |
          git clone --recurse-submodules -b 16.2.1 https://github.com/frida/frida frida16.2.1

      - name: 应用 Rusda 官方补丁
        run: |
          cd frida16.2.1

          # 正确！直接根目录的 frida-core、frida-gum！
          for f in ../rusda/16.2.1/frida-core/*; do
            patch -d frida-core -p1 < "$f" || true
          done

          for f in ../rusda/16.2.1/frida-gum/*; do
            patch -d frida-gum -p1 < "$f" || true
          done

      - name: Build frida-server         
        run: |           
          make core-android-x86_64 
      - name: Copy binary         
        run: |          
          cp build/frida-android-x86_64/bin/frida-server ./frida-server-x86_64 
      - name: Upload artifact         
        uses: actions/upload-artifact@v4         
        with:          
         name: frida-server-florida-16.1.10-x86_64          
         path: frida-server-x86_64           
         if-no-files-found: error
